matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      addons:
       apt:
         packages:
           - gcc-4.8
           - g++-4.8
           - cmake

   - os: linux
     dist: trusty
     language: cpp
     compiler: gcc
     if: tag IS present
     addons:
      apt:
        packages:
          - gcc-6
          - g++-6
          - cmake

script:
     - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/tmp .
     - cmake --build .
     - cmake --build . --target test
     - cmake --build . --target install
